--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: additional_services; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.additional_services (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    is_taxed boolean NOT NULL,
    liquidation_id bigint NOT NULL,
    price real NOT NULL,
    status character varying(255) NOT NULL,
    tariff_rate real NOT NULL,
    CONSTRAINT additional_services_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT additional_services_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.additional_services OWNER TO ptcdemo;

--
-- Name: additional_services_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.additional_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.additional_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    address character varying(255),
    birth_date date NOT NULL,
    email character varying(255),
    first_name character varying(150) NOT NULL,
    id_document_number character varying(50) NOT NULL,
    id_document_type character varying(20) NOT NULL,
    last_name character varying(150) NOT NULL,
    nationality character varying(100),
    phone_number character varying(20),
    CONSTRAINT customers_id_document_type_check CHECK (((id_document_type)::text = ANY ((ARRAY['PASSPORT'::character varying, 'DNI'::character varying, 'DRIVER_LICENSE'::character varying, 'RUC'::character varying, 'CE'::character varying])::text[])))
);


ALTER TABLE public.customers OWNER TO ptcdemo;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_publication; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.event_publication (
    id uuid NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255),
    listener_id character varying(255),
    publication_date timestamp(6) with time zone,
    serialized_event character varying(255)
);


ALTER TABLE public.event_publication OWNER TO ptcdemo;

--
-- Name: flight_bookings; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.flight_bookings (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    aeroline character varying(255) NOT NULL,
    aeroline_booking_code character varying(255) NOT NULL,
    arrival_date timestamp(6) without time zone NOT NULL,
    costamar_booking_code character varying(255),
    currency character varying(255) NOT NULL,
    departure_date timestamp(6) without time zone NOT NULL,
    destiny character varying(255) NOT NULL,
    flight_service_id bigint NOT NULL,
    origin character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    tkt_numbers character varying(255) NOT NULL,
    total_price real NOT NULL,
    CONSTRAINT flight_bookings_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT flight_bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.flight_bookings OWNER TO ptcdemo;

--
-- Name: flight_bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.flight_bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flight_services; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.flight_services (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    is_taxed boolean NOT NULL,
    liquidation_id bigint NOT NULL,
    tariff_rate real NOT NULL,
    CONSTRAINT flight_services_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[])))
);


ALTER TABLE public.flight_services OWNER TO ptcdemo;

--
-- Name: flight_services_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.flight_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO ptcdemo;

--
-- Name: hotel_bookings; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.hotel_bookings (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    check_in timestamp(6) without time zone NOT NULL,
    check_out timestamp(6) without time zone NOT NULL,
    currency character varying(255) NOT NULL,
    hotel character varying(255) NOT NULL,
    hotel_service_id bigint NOT NULL,
    price_by_night real NOT NULL,
    room character varying(255) NOT NULL,
    room_description character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT hotel_bookings_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT hotel_bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.hotel_bookings OWNER TO ptcdemo;

--
-- Name: hotel_bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.hotel_bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotel_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotel_services; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.hotel_services (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    is_taxed boolean NOT NULL,
    liquidation_id bigint NOT NULL,
    tariff_rate real NOT NULL,
    CONSTRAINT hotel_services_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[])))
);


ALTER TABLE public.hotel_services OWNER TO ptcdemo;

--
-- Name: hotel_services_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.hotel_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotel_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: incidencies; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.incidencies (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    amount real,
    incidency_date timestamp(6) without time zone NOT NULL,
    incidency_status character varying(255) NOT NULL,
    liquidation_id bigint NOT NULL,
    reason character varying(500) NOT NULL,
    CONSTRAINT incidencies_incidency_status_check CHECK (((incidency_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.incidencies OWNER TO ptcdemo;

--
-- Name: incidencies_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.incidencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incidencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: liquidations; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.liquidations (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    companion integer NOT NULL,
    currency_rate real NOT NULL,
    customer_id bigint NOT NULL,
    payment_deadline timestamp(6) without time zone NOT NULL,
    payment_status character varying(255) NOT NULL,
    staff_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    total_amount real NOT NULL,
    total_amount_usd real,
    total_commission_pen real,
    total_commission_usd real,
    CONSTRAINT liquidations_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'ON_COURSE'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT liquidations_status_check CHECK (((status)::text = ANY ((ARRAY['IN_QUOTE'::character varying, 'PENDING'::character varying, 'ON_COURSE'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.liquidations OWNER TO ptcdemo;

--
-- Name: liquidations_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.liquidations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.liquidations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    message character varying(500) NOT NULL,
    reference_id character varying(255),
    scope character varying(255) NOT NULL,
    title character varying(200),
    type character varying(255) DEFAULT 'SYSTEM_INFO'::character varying NOT NULL,
    reference_type character varying(50),
    CONSTRAINT notifications_scope_check CHECK (((scope)::text = ANY ((ARRAY['ALL'::character varying, 'SELF'::character varying, 'OTHERS'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO ptcdemo;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    amount real NOT NULL,
    liquidation_id bigint NOT NULL,
    method character varying(255) NOT NULL,
    validation_status character varying(255) NOT NULL,
    currency character varying(255) DEFAULT 'PEN'::character varying NOT NULL,
    evidence_url character varying(255),
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying, 'YAPE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT payments_validation_status_check CHECK (((validation_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VALID'::character varying, 'INVALID'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO ptcdemo;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(512) NOT NULL,
    refresh_token character varying(512) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    refresh_expires_at timestamp without time zone NOT NULL,
    user_agent character varying(500),
    ip_address character varying(45),
    is_revoked boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.sessions OWNER TO ptcdemo;

--
-- Name: TABLE sessions; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON TABLE public.sessions IS 'Stores JWT authentication sessions for users';


--
-- Name: COLUMN sessions.id; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.id IS 'Primary key';


--
-- Name: COLUMN sessions.user_id; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.user_id IS 'Foreign key to users table';


--
-- Name: COLUMN sessions.token; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.token IS 'JWT access token';


--
-- Name: COLUMN sessions.refresh_token; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.refresh_token IS 'JWT refresh token for token rotation';


--
-- Name: COLUMN sessions.expires_at; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.expires_at IS 'Access token expiration timestamp';


--
-- Name: COLUMN sessions.refresh_expires_at; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.refresh_expires_at IS 'Refresh token expiration timestamp';


--
-- Name: COLUMN sessions.user_agent; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.user_agent IS 'Browser/client user agent string';


--
-- Name: COLUMN sessions.ip_address; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.ip_address IS 'Client IP address';


--
-- Name: COLUMN sessions.is_revoked; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.is_revoked IS 'Whether the session has been manually revoked';


--
-- Name: COLUMN sessions.is_active; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.is_active IS 'Whether the session is still active';


--
-- Name: COLUMN sessions.created_date; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.created_date IS 'Session creation timestamp';


--
-- Name: COLUMN sessions.updated_date; Type: COMMENT; Schema: public; Owner: ptcdemo
--

COMMENT ON COLUMN public.sessions.updated_date IS 'Last update timestamp';


--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

CREATE SEQUENCE public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.sessions_id_seq OWNER TO ptcdemo;

--
-- Name: sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: ptcdemo
--

ALTER SEQUENCE public.sessions_id_seq OWNED BY public.sessions.id;


--
-- Name: staff; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.staff (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    currency character varying(10) NOT NULL,
    hire_date timestamp(6) without time zone,
    phone_number character varying(20) NOT NULL,
    role character varying(20) NOT NULL,
    salary real NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT staff_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT staff_role_check CHECK (((role)::text = ANY ((ARRAY['SALES'::character varying, 'COUNTER'::character varying, 'ACCOUNTING'::character varying, 'OPERATIONS'::character varying, 'SUPERADMIN'::character varying, 'SUPPORT'::character varying])::text[])))
);


ALTER TABLE public.staff OWNER TO ptcdemo;

--
-- Name: staff_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tour_services; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.tour_services (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    is_taxed boolean NOT NULL,
    liquidation_id bigint NOT NULL,
    tariff_rate real NOT NULL,
    CONSTRAINT tour_services_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[])))
);


ALTER TABLE public.tour_services OWNER TO ptcdemo;

--
-- Name: tour_services_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.tour_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tour_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tours; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.tours (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    currency character varying(255) NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    place character varying(255) NOT NULL,
    price real NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    tour_service_id bigint NOT NULL,
    CONSTRAINT tours_currency_check CHECK (((currency)::text = ANY ((ARRAY['PEN'::character varying, 'USD'::character varying])::text[]))),
    CONSTRAINT tours_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[])))
);


ALTER TABLE public.tours OWNER TO ptcdemo;

--
-- Name: tours_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.tours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.user_notifications (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    notification_id bigint NOT NULL,
    read boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_notifications OWNER TO ptcdemo;

--
-- Name: user_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.user_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: ptcdemo
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_active boolean,
    updated_date timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    user_name character varying(100)
);


ALTER TABLE public.users OWNER TO ptcdemo;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: ptcdemo
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions id; Type: DEFAULT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.sessions ALTER COLUMN id SET DEFAULT nextval('public.sessions_id_seq'::regclass);


--
-- Name: additional_services additional_services_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.additional_services
    ADD CONSTRAINT additional_services_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: event_publication event_publication_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.event_publication
    ADD CONSTRAINT event_publication_pkey PRIMARY KEY (id);


--
-- Name: flight_bookings flight_bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.flight_bookings
    ADD CONSTRAINT flight_bookings_pkey PRIMARY KEY (id);


--
-- Name: flight_services flight_services_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.flight_services
    ADD CONSTRAINT flight_services_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: hotel_bookings hotel_bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.hotel_bookings
    ADD CONSTRAINT hotel_bookings_pkey PRIMARY KEY (id);


--
-- Name: hotel_services hotel_services_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.hotel_services
    ADD CONSTRAINT hotel_services_pkey PRIMARY KEY (id);


--
-- Name: incidencies incidencies_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.incidencies
    ADD CONSTRAINT incidencies_pkey PRIMARY KEY (id);


--
-- Name: liquidations liquidations_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.liquidations
    ADD CONSTRAINT liquidations_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_refresh_token_key; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_refresh_token_key UNIQUE (refresh_token);


--
-- Name: sessions sessions_token_key; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_token_key UNIQUE (token);


--
-- Name: staff staff_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (id);


--
-- Name: tour_services tour_services_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.tour_services
    ADD CONSTRAINT tour_services_pkey PRIMARY KEY (id);


--
-- Name: tours tours_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT tours_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: customers uk6v6x92wb400iwh6unf5rwiim4; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT uk6v6x92wb400iwh6unf5rwiim4 UNIQUE (phone_number);


--
-- Name: staff uk7qatq4kob2sr6rlp44khhj53g; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT uk7qatq4kob2sr6rlp44khhj53g UNIQUE (user_id);


--
-- Name: users ukk8d0f2n7n88w1a16yhua64onx; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukk8d0f2n7n88w1a16yhua64onx UNIQUE (user_name);


--
-- Name: customers ukqm44dpcxa4tf5ru8hpi754ygo; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukqm44dpcxa4tf5ru8hpi754ygo UNIQUE (id_document_number);


--
-- Name: customers ukrfbvkrffamfql7cjmen8v976v; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukrfbvkrffamfql7cjmen8v976v UNIQUE (email);


--
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: ptcdemo
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_sessions_expires_at; Type: INDEX; Schema: public; Owner: ptcdemo
--

CREATE INDEX idx_sessions_expires_at ON public.sessions USING btree (expires_at);


--
-- Name: idx_sessions_is_revoked; Type: INDEX; Schema: public; Owner: ptcdemo
--

CREATE INDEX idx_sessions_is_revoked ON public.sessions USING btree (is_revoked);


--
-- Name: idx_sessions_refresh_token; Type: INDEX; Schema: public; Owner: ptcdemo
--

CREATE INDEX idx_sessions_refresh_token ON public.sessions USING btree (refresh_token);


--
-- Name: idx_sessions_token; Type: INDEX; Schema: public; Owner: ptcdemo
--

CREATE INDEX idx_sessions_token ON public.sessions USING btree (token);


--
-- Name: idx_sessions_user_id; Type: INDEX; Schema: public; Owner: ptcdemo
--

CREATE INDEX idx_sessions_user_id ON public.sessions USING btree (user_id);


--
-- Name: tours fk72n25t9awatskhn628h7ickf9; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT fk72n25t9awatskhn628h7ickf9 FOREIGN KEY (tour_service_id) REFERENCES public.tour_services(id);


--
-- Name: liquidations fk7bsb6ojpoauiqx6iltgmscm6t; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.liquidations
    ADD CONSTRAINT fk7bsb6ojpoauiqx6iltgmscm6t FOREIGN KEY (staff_id) REFERENCES public.staff(id);


--
-- Name: sessions fk_sessions_user; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: staff fkdlvw23ak3u9v9bomm8g12rtc0; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT fkdlvw23ak3u9v9bomm8g12rtc0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: hotel_bookings fkffn6h2hjue4upwxdsel7sw9xm; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.hotel_bookings
    ADD CONSTRAINT fkffn6h2hjue4upwxdsel7sw9xm FOREIGN KEY (hotel_service_id) REFERENCES public.hotel_services(id);


--
-- Name: flight_bookings fkgq5sgegbujjpw8b5ufua6gdwl; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.flight_bookings
    ADD CONSTRAINT fkgq5sgegbujjpw8b5ufua6gdwl FOREIGN KEY (flight_service_id) REFERENCES public.flight_services(id);


--
-- Name: hotel_services fkhdjxtbsad6mgw44s8xej9dhl; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.hotel_services
    ADD CONSTRAINT fkhdjxtbsad6mgw44s8xej9dhl FOREIGN KEY (liquidation_id) REFERENCES public.liquidations(id);


--
-- Name: incidencies fkiscx02gjhu0dpnnykep722qj7; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.incidencies
    ADD CONSTRAINT fkiscx02gjhu0dpnnykep722qj7 FOREIGN KEY (liquidation_id) REFERENCES public.liquidations(id);


--
-- Name: additional_services fkn6weuka35wc914sbf18x8wv8u; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.additional_services
    ADD CONSTRAINT fkn6weuka35wc914sbf18x8wv8u FOREIGN KEY (liquidation_id) REFERENCES public.liquidations(id);


--
-- Name: payments fko5c8q0f1pm48xdfwgi4eyql1l; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fko5c8q0f1pm48xdfwgi4eyql1l FOREIGN KEY (liquidation_id) REFERENCES public.liquidations(id);


--
-- Name: liquidations fko8s2dc413c4ooxyxj27858aba; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.liquidations
    ADD CONSTRAINT fko8s2dc413c4ooxyxj27858aba FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: user_notifications fkovvx0ab3h8s9lrm6fppuadn7d; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fkovvx0ab3h8s9lrm6fppuadn7d FOREIGN KEY (notification_id) REFERENCES public.notifications(id);


--
-- Name: flight_services fksqx9ba2tl40orid2ebiubvkft; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.flight_services
    ADD CONSTRAINT fksqx9ba2tl40orid2ebiubvkft FOREIGN KEY (liquidation_id) REFERENCES public.liquidations(id);


--
-- Name: tour_services fkte3400vf48tyvad3e77flupj5; Type: FK CONSTRAINT; Schema: public; Owner: ptcdemo
--

ALTER TABLE ONLY public.tour_services
    ADD CONSTRAINT fkte3400vf48tyvad3e77flupj5 FOREIGN KEY (liquidation_id) REFERENCES public.liquidations(id);


--
-- PostgreSQL database dump complete
--

